name: app
description: App which manages PassKit files.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: 3.22.3

dependencies:
  android_intent_plus: ^5.0.2
  content_resolver: ^0.3.3
  cupertino_icons: ^1.0.8
  desktop_drop: ^0.6.1
  file_picker: ^10.2.1
  floor: ^1.5.0
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_fonts: ^6.2.1
  http: ^1.2.1
  intl: any
  package_info_plus: ^8.0.0
  passkit: ^0.0.2
  passkit_ui: ^0.0.1
  path: ^1.9.0
  path_provider: ^2.0.0
  receive_intent: ^0.2.4
  screen_brightness: ^2.1.6
  share_plus: ^11.0.0
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  sqlite3_flutter_libs: ^0.5.0
  url_launcher: ^6.3.0
  wakelock_plus: ^1.2.5

dependency_overrides:
  passkit:
    path: ../passkit
  passkit_ui:
    path: ../passkit_ui

dev_dependencies:
  build_runner: ^2.4.6
  floor_generator: ^1.5.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/examples/
