name: apple_passkit
description: Plugin to deal with Apple Wallet & PKPass files on iOS. You can check for availabililty and add them.
version: 1.0.0+1
repository: https://github.com/ueman/passkit/
issue_tracker: https://github.com/ueman/passkit/issues
topics:
  - passkit
  - pkpass
  - apple-wallet
  - wallet
  - passbook

screenshots:
  - description: "Screenshot of a PkPass of the boarding pass type"
    path: assets/boarding_pass.webp

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      ios:
        pluginClass: ApplePasskitPlugin
