name: passkit_ui
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.0.7 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  barcode_widget: ^2.0.4
  csslib: ^0.17.2
  passkit: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  passkit:
    path: ../passkit

flutter: