name: passkit
description: "Pure Dart library which can read Apple's PKPass files. Works on servers too."
version: 0.0.2
repository: https://github.com/ueman/passkit
issue_tracker: https://github.com/ueman/passkit/issues
topics:
  - passkit
  - pkpass
  
environment:
  sdk: ^3.0.0

dependencies:
  archive: ^3.3.5
  barcode: ^2.2.3
  csslib: ^1.0.0
  json_annotation: ^4.9.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
  build_runner: ^2.3.2
  json_serializable: ^6.8.0
