name: passkit
description: Pure Dart library which can create and read Apple's PkPass files (which are usually shown in Apple Wallet). Works on servers and in apps.
version: 1.1.0
repository: https://github.com/ueman/passkit
issue_tracker: https://github.com/ueman/passkit/issues
topics:
  - passkit
  - pkpass
  - apple-wallet
  - wallet
  - passbook

screenshots:
  - description: "Screenshot of a PkPass of the boarding pass type"
    path: assets/boarding_pass.webp

funding:
  - https://github.com/sponsors/ueman

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  archive: ^4.0.0
  collection: ^1.18.0
  crypto: ^3.0.0
  csslib: ^1.0.0
  http: ^1.2.0
  http_parser: ^4.0.0
  image: ^4.1.1
  intl: ">=0.18.0 <0.21.0" # This makes it possible to use this library on older Flutter versions
  json_annotation: ^4.8.0
  meta: ^1.0.0
  pkcs7: ^1.0.0
  pointycastle: ^4.0.0

dev_dependencies:
  build_runner: ^2.3.2
  json_serializable: ^6.8.0
  lints: ^4.0.0
  test: ^1.21.0
